In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

41
0.8548881879042122


In [4]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,3)))

[36 49 52]
[[30 39 29 64]
 [26 55 27 61]
 [30 72 12 75]]
[[[72 58 71]
  [91 18 61]
  [18 91 43]
  [38 75 40]]

 [[ 8  0 22]
  [20 29 15]
  [49 79 23]
  [87 16 20]]

 [[34  2  2]
  [ 5 97 53]
  [39 13 35]
  [85  3 45]]]


In [6]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.8710572674092901
[0.80537064 0.74131184 0.92670737]
[[0.2148474  0.03484591 0.57319208]
 [0.56282351 0.45601351 0.06869101]]


In [9]:
a = random.randint(100,size=(3,2)).ravel()
a

array([95, 63, 45, 62, 93, 48])

In [10]:
#single element will be selected
random.choice(a)

93

In [13]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 4, 2, 3],
       [1, 3, 5, 2],
       [2, 3, 5, 2],
       [4, 5, 1, 2]])

### Pandas:
1. Data manipulation,analysis and cleaning
2. Tabular,Unlabelled

### Creating a DataFrame 
1. using 2 dictionaries
2. simple dictionary --> DataFrame

In [21]:
#Using 2 dictionaries
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':6,'b':7,'c':8,'d':9,'e':10}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       6
b      2       7
c      3       8
d      4       9
e      5      10

In [22]:
#simple dictionary --> DataFrame
d1 = {"name":["bharadwaj","venu","sai"],"address":["hyd","orrisa","KD"]}
df1 = pd.DataFrame(d1)
df1

name address
0  bharadwaj     hyd
1       venu  orrisa
2        sai      KD

In [23]:
#using Series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,34.3,45.5,67.4,67.78,34.45,24.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    24.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the DataFrame:
1. loc
2. iloc

In [24]:
df3["column2"]

0    12.23
1    23.34
2    34.30
3    45.50
4    67.40
5    67.78
6    34.45
7    24.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [27]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    34.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    24.34       h
8    67.40       i
9    23.00       j

In [28]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [30]:
#Extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    34.30
3        4    45.50
4        5    67.40
5        6    67.78

In [32]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [31]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [33]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [34]:
df3.shape

(10, 3)

In [35]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [36]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [37]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.30       c
3        4    45.50       d
4        5    67.40       e

In [38]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.30       c

In [39]:
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    24.34       h
8        9    67.40       i
9       10    23.00       j

In [40]:
df3.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [42]:
df3.sample()

column1  column2 column3
0        1    12.23       a

In [43]:
df3.sample(2)

column1  column2 column3
0        1    12.23       a
7        8    24.34       h

In [44]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  39.974000
std     3.02765  20.949008
min     1.00000  12.230000
25%     3.25000  23.590000
50%     5.50000  34.375000
75%     7.75000  61.925000
max    10.00000  67.780000

In [47]:
df3 = df3.rename(columns={"column1":"First",
                    "column2":"Second",
                    "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   34.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   24.34     h
8      9   67.40     i
9     10   23.00     j